---
title: "My english activity log"
---

**13/10/19**: I worked on my blog. I found websites to work on my portfolio's topic. I've consulted the "*DailyMail*" website and chosen two articles. 
I learned the specific vocabulary, and i've started the analysis of my 1st article.

**18/10/19**: I finished the analysis table and the vocabulary. The post of my first article is finalised. I watched a YouTube video. 

**20/10/19**: I finalised my first aricle and brought modifications. 
I watched a youtube vidéo for my topic (*koalas*).

**31/10/2019**: I worked on my second article. I found and choosed this article that will be posted on this blog speedly. I always do a few listening exercices with the *music* i'm listening when i go to school. Nowadays it's a bit difficult to concentrate myself on the *lyrics*, but i'll do this until i understand the pieces of music i'm always listening to.

**02/11/2019**: The second article has been posted. I've done the vocabulary table, and the analysis table. The section "About" has been actualised to become clearer. 
In a second time, i found my third article for my portfolio. 

**29/11/2019**: I worked on my protfolio. I found new articles, very interesting, that will be posted very quickly. I looked after the news around the world, with the *BBC App*. I always listen to music when i'm going to school, and now I note that it's more simply for me to understand the *lyrics*, and the signifcation of the music. 

**16/02/2020**: After a long time whithout work on my website, I worked hard to post my two nex articles. The first one (n°6) talks about the possible moving of the koalas from Australia, and the second one discusses the solution that would be the most important to preserve the genetical diversity of the koalas. 
During my free time, I study my vocabulary with the "Quizlet" App. 
Unfortunatelly, I don't have much free time to watch series or vidéos, but today, I found a nice article that is talking about the first sequencing of the koala's genome. It was not enough recent to publish it on my blog, so I put the link here. 
<https://www.earlham.ac.uk/newsroom/koala-genome-cracked-down-under-help-save-species>
