---
title: "English Activity Log"
description: |
  Here are listed all my activities in relation with English : Youtube videos, reviews, books, articles...
author:
  - name: AdrienRoulez
date: 02-19-2020
preview: speak_english.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**13/10/19**: I worked on my blog. I found websites to work on my portfolio's topic. I've consulted the "*DailyMail*" website and chosen two articles. 
I learned the specific vocabulary, and i've started the analysis of my 1st article.

**18/10/19**: I finished the analysis table and the vocabulary. The post of my first article is finalised. I watched a YouTube video. 

**20/10/19**: I finalised my first aricle and brought modifications. 
I watched a youtube vidéo for my topic (koalas).

**31/10/2019**: I worked on my second article. I found and choosed this article that will be posted on this blog speedly.

**02/11/2019**: The second article has been posted. I've done the vocabulary table, and the analysis table. The section "About" has been actualised to become clearer. 
In a second time, i found my third article for my portfolio. 

**30/11/2019**: I worked on my fourth article, found the specific vocabulary, and understood more words than ever. This article has been posted on my blog, and it's now accessible with the analysis. I also found my fifth article, and i'll work on very soon. Since two or three weeks, when i go to school, and i'm listening my music, i try to understand all the lyrics. Sometimes It's a bit difficult, but at the end, it will be effective for me to improve my comprehension of the language.

**01/12/2019**: I worked on my fifth article, and read a lot of others. I post here all the links of the articles that i've read. These articles will not be posted and analysed on my blog, but i think it's important for the readers to have access to anothers articles. 

<https://www.bbc.com/news/av/science-environment-47708374/longleat-koala-conservation-scheme-working-despite-death>

<https://www.bbc.com/news/topics/ceddn94wgnnt/koalas>

<https://www.bbc.com/news/world-australia-50230701>

<https://www.sciencedaily.com/releases/2019/10/191010113231.htm>

**16/02/2020**: After a long time whithout working on my website, I worked hard to post my two nex articles. The first one (n°6) talks about the possible moving of the koalas from Australia, and the second one discusses the solution that would be the most important to preserve the genetical diversity of the koalas. 
During my free time, I study my vocabulary with the "Quizlet" App. 
Unfortunatelly, I don't have much free time to watch series or vidéos, but today, I found a nice article that is talking about the first sequencing of the koala's genome. It was not enough recent to publish it on my blog, so I put the link here. 

<https://www.earlham.ac.uk/newsroom/koala-genome-cracked-down-under-help-save-species>



