---
title: "Virtual reality and drones help to predict and protect koala habitat"
description: |
  This article explains how to proceed to map the natural habitat of the koalas' populations, and so protect it.
author:
  - name: AdrienRoulez
    url: {}
date: 04-05-2020
preview: images.jfif
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Details

* **Source of the article**

<https://phys.org/news/2019-12-virtual-reality-drones-koala-habitat.html>

* **Words number**
600

## Vocabulary

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| multi-pronged approach | An approach with different parts |
| hanging around in | Here to be in a specific and favourite location |
| facilities | A place, amenity, or piece of equipment provided for a particular purpose. |
| playgrounds | An outdoor area provided for children to play in, especially at a school or public park. |
| counteract | Act against (something) in order to reduce its force or neutralize it. |
| surrounding | All round a particular place |
| involved | Cause to participate in an activity or situation. |
| likelihood | The state or fact of something's being likely; probability. |
|three-pronged  | Having three projecting, pointed parts. |

## Analysis table

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Dr. Catherine Leigh, Associate Investigator with ACEMS|
| Published in?                | December 11, 2019 |
| General topic?               | The general topic of this article is the fact that there are mathematic and modern solutions to protect the koalas. |
| Procedure/what was examined? | A combination of virtual reality (VR), aerial thermal-imaging and ground surveys can be used to study the distribution of the koalas. This combination is after used to build a better statistical model for predicting the location of koalas. The researchers used ground survey information captured between 2012 and 2017 from Alexander Clarke Park in Loganholme. In addition, the researchers surveyed the area from the air using thermal cameras near sunrise to counteract the fact that it is difficult to monitor the populations from the ground. The third part of the study involved sending researchers out to some of the 82 specific locations in the area where koalas were known to either be or not be, to take 360-degree images. Those images were shown to experts with VR headsets. The advantage of the VR is that we can bring the environment at the researchers.|
| Conclusions/discovery?       | If we are able to know and predict where the koalas are, we are able to know the zones that need to be protected and monitored. The researchers proved that this combination of VR-prompted expert information, thermal imagery and ground surveys, is 75 percent more accurate to predict koalas' locations than ground surveys alone. This method could be used by authorities in order to obtain essential informations to protect the species. |
| Remaining questions?         |  |
